#  Please refer to the wiki(https://github.com/nlef/moonraker-telegram-bot/wiki) for detailed information on how to configure the bot

[bot]
server: localhost
bot_token: 8983058219:AAGC5MDPrglt2YOFcQxxawXoopMkMK5MPEM
chat_id: 8910642485

[camera]
host: http://localhost:8080/?action=stream
type: mjpeg

[progress_notification]
percent: 25
height: 0
time: 0

[timelapse]
cleanup: true
height: 0.2
time: 15 #0 for cinematic
target_fps: 20 #20 for cinematic
min_lapse_duration: 10
max_lapse_duration: 60
